version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      # FOR DOCKER - POSTGRES_DB
      POSTGRES_DB: ${NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  
  # webapp:
  #   restart: always
  #   build:
  #     context: ./
  #   ports: 
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  #   # FOR DOCKER
  #   command: ["bash", "-c", "sleep 30 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]


  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   # volumes:
  #   #   - ./redis/redis_db:/data

  # worker:
  #   restart: always
  #   build:
  #     context: ./
  #   volumes:
  #     - ./invoices:/app/invoices # Почему-то биндится папка invoices именно в контейнере worker, а не webapp
  #   depends_on:
  #     - webapp
  #   # FOR DOCKER
  #   command: celery -A eshop worker -l info
  #   # command: celery -A eshop worker -l info -P eventlet

  # flower:
  #   build:
  #     context: ./
  #   restart: always
  #   depends_on:
  #     - worker
  #   ports: 
  #     - "5555:5555"
  #   # command: celery -A eshop flower -l info -P eventlet
  #   # FOR DOCKER
  #   command: celery -A eshop flower -l info --persistent=True

  # beat:
  #   restart: always
  #   build:
  #     context: ./
  #   depends_on:
  #     - flower
  #   command: celery -A eshop beat -l info