# Generated by Django 5.0.3 on 2024-03-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
