# Generated by Django 5.0.3 on 2024-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='brand',
            field=models.ManyToManyField(related_name='subcategory', to='products.brand'),
        ),
    ]
