# Generated by Django 5.0.3 on 2024-03-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_brand_subcategory_subcategory_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
