# Generated by Django 5.0.3 on 2024-04-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_subcategory_category_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(related_name='brand', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.category'),
            preserve_default=False,
        ),
    ]
