# Generated by Django 5.0.3 on 2024-03-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_subcategory_category_remove_subcategory_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(null=True, related_name='products', to='products.attribute'),
        ),
    ]
