# Generated by Django 5.0.3 on 2024-06-16 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_image_product_variant_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant'),
        ),
    ]
