# Generated by Django 5.0.3 on 2024-06-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_image_product_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'Attribute Image',
                'verbose_name_plural': 'Attribute Images',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='products.attributeimage'),
        ),
    ]
