# Generated by Django 5.0.3 on 2024-04-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brand_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
