# Generated by Django 5.0.3 on 2024-06-17 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_attributeimage_attribute_attribute_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, 'The price must be equal or greater than 0.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0, 'The price must be equal or greater than 0.')]),
        ),
    ]
