# Generated by Django 5.0.3 on 2024-04-15 19:16

import orders.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=orders.utils.generate_order_number, max_length=10, unique=True),
        ),
    ]
