# Generated by Django 5.0.3 on 2024-05-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'panding'), (2, 'completed'), (3, 'shipped'), (4, 'delivered'), (5, 'cancelled')], default=1, max_length=7),
        ),
    ]
